### ISSUE TITLE
Request for comment: Quickstart vs enabling 0-handcraft

### ISSUE THREAD

**Issue by oorzkws** [DanielZlotin/FactorioFastLazyBastard#2]
Hi,

I ran across this mod to enable a no-handcraft run (specifically with PyMods), however it seems to have some things that are more in the category of "quick start" than simply enabling lazy bastard. I would like your opinion as maintainer on the following perceived issues and proposed changes, which I would be happy to write and pull request.

- Crashed generator makes more than the combined power use of other crash site entities
  - My feedback would be to switch the crashed assembler and lab to burner energy sources and disable the generator
- Player starts with extra items, especially cliff explosives
  - Personally I would prefer to just remove these, but would you like them gated behind a setting?
- Crashed lab isn't necessary for most mod-sets
  - Remove or setting?
- Crashed assemblers have ingredient count limits that can prevent crafting certain recipes for progression
  - Disable ingredient limit
- Pollution coloring isn't really a related feature
  - Remove or setting? Also covered by other mods that could be recommended like some others already are
  
Long short is I figured I would ask what's appropriate before I work on a pull request. Thanks!

**Comment by DanielZlotin** [comment]
thanks for the feedback, appreciated, sorry for the long delay

1. I really like the crash site improvised generator graphics and idea, but I agree it should only be able to power just the starting entities and no more, so lower power generation and maybe convert it to use fuel instead of "free energy"?

2. The cliff explosives are a personal pet peeve, that tech is unlocked way too late when the base already has a basic shape (going around small cliffs in the starting area), I like my base to be neat from the start and I would rather not disable cliffs completely. So I figured some remnants of the crashed ship looks like giant explosive shells, why not fashion some bootstrapping terraforming tools ;) I don't mind it being behind a setting

3. I see your point, but I wanted some use for that cool looking entity. More to your next point, because currently you have the ability to research automation from the get-go using that improvised lab, then improvised assemblers' ingredient limit makes more sense, no?

4. Yea I will split this part out to a new mod (unless this already exists?)

wdyt?
